version: "3.7"

services:
  app:
    container_name: rentx
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

  postgresdb:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
