version: "3.7"

services:
  postgresdb:
    image: bitnami/postgresql:latest
    container_name: ${TYPEORM_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  mongodb:
    image: bitnami/mongodb:latest
    container_name: ${MONGODB_CONTAINER_NAME}
    # environment:
    #   - ALLOW_EMPTY_PASSWORD=no
    #   - MONGODB_USERNAME=${MONGO_USER}
    #   - MONGODB_PASSWORD=${MONGO_PASS}
    #   - MONGODB_DATABASE=${MONGO_DB}
    network_mode: host

  redisdb:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    network_mode: host

volumes:
  pgdata:
    driver: local
