version: "3.7"

services:
  app:
    container_name: rentx
    build: .
    volumes:
      - .:/usr/app
    network_mode: host

  postgresdb:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  pgdata:
    driver: local